ores:
  coal_ore:
    cooldown: 10
    pick-level: 1

tags:
  og:
    released: 1688578200000
    description: This tag is given to people who are active during the first season
    display: <gray>[<yellow><b>OG</b><gray>]
  linked:
    released: 1688578200000
    description: Unlocked after linking your discord and minecraft accounts
    display: <gray>[<blue>Linked<gray>]
