name: Cavern
version: '${project.version}'
main: me.phill310.cavern.Main
api-version: '1.19'
load: STARTUP
softdepend: [ Vault ]
authors: [ Phill310 ]
description: Wacky skymining gen thingy
commands:
  tag:
    description: Opens tag menu
    aliases: tags
  chatcolor:
    description: Change your chatcolor
    aliases: chatcolors
  ore:
    description: Opens a menu with all of the ores
    aliases: ores
  cavern:
    description: Base command
    permission: cavern.admin
